import { BellRing, Megaphone, Users } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { listNotifications } from "@/lib/queries";
import { DarkPanel, IconTile, MetricCard, Pill, ProgressBar, SectionHeading } from "@/components/ui/primitives";
import { NotificationComposer } from "@/components/admin/forms";
import { formatDate, formatTime, relativeDay } from "@/lib/format";
import { pastelFor, type PastelKey } from "@/lib/tokens";

export const dynamic = "force-dynamic";

const TYPE_TONE: Record<string, "neutral" | "positive" | "warning" | "danger" | "info"> = {
  ANNOUNCEMENT: "info",
  PAYMENT: "positive",
  MEMBERSHIP: "warning",
  HOLIDAY: "neutral",
  EMERGENCY: "danger",
  EVENT: "info",
  TRAINER: "neutral",
};

export default async function CommunicationPage() {
  const admin = await requireAdmin();
  const notifications = await listNotifications(admin.gymId);

  const totalRecipients = notifications.reduce((sum, row) => sum + row.recipients, 0);
  const totalRead = notifications.reduce((sum, row) => sum + row.read_count, 0);
  const readRate = totalRecipients ? Math.round((totalRead / totalRecipients) * 100) : 0;

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-[26px] font-semibold tracking-tight text-ghost sm:text-[30px]">Communication</h1>
          <p className="mt-1 text-[13px] text-ghost-dim">Announcements, automated reminders and readership analytics</p>
        </div>
        <NotificationComposer />
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        <MetricCard accent="cyan" label="Announcements" value={String(notifications.length)} caption="Sent to the community" icon={<Megaphone size={16} />} />
        <MetricCard accent="lavender" label="Deliveries" value={String(totalRecipients)} caption="Recipient records created" icon={<Users size={16} />} />
        <MetricCard accent="cream" label="Read rate" value={`${readRate}%`} caption="Across all announcements" icon={<BellRing size={16} />} />
      </div>

      <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]">
        <div className="space-y-4">
          {notifications.map((notification, index) => {
            const accent = pastelFor(index) as PastelKey;
            const rate = notification.recipients ? Math.round((notification.read_count / notification.recipients) * 100) : 0;
            return (
              <DarkPanel key={notification.id}>
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div className="flex items-start gap-4">
                    <IconTile accent={accent}>
                      <BellRing size={16} />
                    </IconTile>
                    <div>
                      <p className="text-[15px] font-semibold text-ghost">{notification.title}</p>
                      <p className="mt-1 max-w-2xl text-[12.5px] leading-relaxed text-ghost-dim">{notification.message}</p>
                      <div className="mt-3 flex flex-wrap items-center gap-3">
                        <Pill tone={TYPE_TONE[notification.type] ?? "neutral"}>{notification.type}</Pill>
                        <span className="text-[11.5px] text-ghost-muted">
                          {formatDate(notification.createdAt)} · {formatTime(notification.createdAt)} · {notification.audience}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="min-w-[140px]">
                    <p className="text-[11.5px] text-ghost-muted">Read by</p>
                    <p className="gf-num text-[16px] font-semibold text-ghost">
                      {notification.read_count}/{notification.recipients}
                    </p>
                    <div className="mt-2">
                      <ProgressBar value={rate} accent="#8DDDEB" track="rgba(255,255,255,.08)" height={6} />
                    </div>
                  </div>
                </div>
              </DarkPanel>
            );
          })}
        </div>

        <div className="space-y-5">
          <DarkPanel>
            <SectionHeading title="Automated reminders" caption="Membership expiry schedule" />
            <ul className="mt-4 space-y-2.5">
              {(admin.gym.reminderDays ?? [30, 15, 7, 3, 1]).map((days) => (
                <li key={days} className="flex items-center justify-between rounded-card border border-white/7 bg-white/4 px-4 py-3">
                  <span className="text-[12.5px] text-ghost-dim">{days} days before expiry</span>
                  <Pill tone="positive">Enabled</Pill>
                </li>
              ))}
            </ul>
            <p className="mt-4 text-[11.5px] text-ghost-muted">
              Reminders are generated by the daily job for every active subscription inside the configured threshold.
            </p>
          </DarkPanel>

          <DarkPanel>
            <SectionHeading title="Templates" caption="One tap messages" />
            <div className="mt-4 space-y-3">
              {[
                { title: "Payment reminder", body: "Hi {name}, ₹{amount} is pending on your membership. Pay at the front desk or via UPI." },
                { title: "Expiry nudge", body: "Your {plan} membership expires in {days} days. Renew today to keep your streak." },
                { title: "Win-back", body: "We miss you at the gym! It’s been {days} days since your last session." },
              ].map((template) => (
                <div key={template.title} className="rounded-card border border-white/7 bg-white/4 p-4">
                  <p className="text-[12.5px] font-semibold text-ghost">{template.title}</p>
                  <p className="mt-1 text-[11.5px] leading-relaxed text-ghost-muted">{template.body}</p>
                </div>
              ))}
            </div>
          </DarkPanel>

          <DarkPanel>
            <SectionHeading title="Delivery health" caption="Last announcement" />
            {notifications[0] ? (
              <div className="mt-4 space-y-2 text-[12.5px] text-ghost-dim">
                <p className="font-semibold text-ghost">{notifications[0].title}</p>
                <p>Sent {relativeDay(notifications[0].createdAt)} to {notifications[0].recipients} people.</p>
                <p className="text-ghost-muted">
                  {notifications[0].read_count} opened · {notifications[0].recipients - notifications[0].read_count} unread
                </p>
              </div>
            ) : (
              <p className="mt-4 text-[12.5px] text-ghost-muted">No announcements sent yet.</p>
            )}
          </DarkPanel>
        </div>
      </div>
    </div>
  );
}
